version: '3'

services:
  database:
    image: library/mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=treatments

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PORT=3306
      - PMA_PASSWORD=123
      - PMA_HOSTS=database
    restart: always
    ports:
      - "8082:80"
