// Code generated by MockGen. DO NOT EDIT.
// Source: database/illnesses.go

// Package mock_database is a generated GoMock package.
package mock_database

import (
	reflect "reflect"
	database "treatment-scheme-organizer/database"

	gomock "github.com/golang/mock/gomock"
)

// MockIllnessesRepository is a mock of IllnessesRepository interface.
type MockIllnessesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIllnessesRepositoryMockRecorder
}

// MockIllnessesRepositoryMockRecorder is the mock recorder for MockIllnessesRepository.
type MockIllnessesRepositoryMockRecorder struct {
	mock *MockIllnessesRepository
}

// NewMockIllnessesRepository creates a new mock instance.
func NewMockIllnessesRepository(ctrl *gomock.Controller) *MockIllnessesRepository {
	mock := &MockIllnessesRepository{ctrl: ctrl}
	mock.recorder = &MockIllnessesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIllnessesRepository) EXPECT() *MockIllnessesRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockIllnessesRepository) Add(title string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", title)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockIllnessesRepositoryMockRecorder) Add(title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockIllnessesRepository)(nil).Add), title)
}

// All mocks base method.
func (m *MockIllnessesRepository) All(limit, offset int) ([]database.Illness, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", limit, offset)
	ret0, _ := ret[0].([]database.Illness)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockIllnessesRepositoryMockRecorder) All(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockIllnessesRepository)(nil).All), limit, offset)
}

// ByID mocks base method.
func (m *MockIllnessesRepository) ByID(id uint) (database.Illness, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", id)
	ret0, _ := ret[0].(database.Illness)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockIllnessesRepositoryMockRecorder) ByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockIllnessesRepository)(nil).ByID), id)
}
